### ISSUE TITLE
Incorrect example for custom servers (Running on Linux guide)

### ISSUE THREAD

**Issue by spiritphyz** [MagicalCodeMonkey/docs.synclounge.tv#11]
Hi, I was following along the [Running on Linux](http://docs.synclounge.tv/self-hosted/linux/) guide and found an error:
```json
"servers":[
          {
             "name":"Your Super Cool Plex Party Server",
             "location":"Space, the Final Frontier",
             "url":"http://synclounge.yourdomain.com",
             "logo":""
          }
],
```
The custom server url key needs to point towards the server endpoint, like `http://synclounge.yourdomain.com/slserver`. It took me a few hours to troubleshoot why I kept getting “cannot connect to server” errors after trying to join a room in the Web UI (of course, this was right before trying to set up a viewing party last night and getting stopped in my tracks).

I found the fix this morning and made a [pull request](https://github.com/MagicalCodeMonkey/docs.synclounge.tv/pull/10) to update the guide.

The rest of the sections in the guide are really accurate, and I was able to get SyncLounge working with the 2 Node servers (webapp and server) and Nginx.

**Comment by MagicalCodeMonkey** [comment]
Merged PR #10! Thanks again!
